### ISSUE TITLE
Sprite delay when turning direction

### ISSUE THREAD

**Issue by NowsfekyBR** [suriyun-mmorpg/UnityMultiplayerARPG_2DAI#1]
I am using the addon, it works very well but I see that there is a sprite delay when turning direction. Can you improve this so that the sprite always turns at the same time you change direction?

**Comment by insthync** [comment]
You can try to fix it by changes codes in `CharacterModel2D` → Play() function from line 145 to
```
        public void Play(AnimationClip2D anim)
        {
            if (anim == playingAnim)
                return;

            playingAnim = anim;
            spriteRenderer.flipX = anim.flipX;
            spriteRenderer.flipY = anim.flipY;
            secsPerFrame = 1f / anim.framesPerSec;
            currentFrame = -1;
            playing = true;
            nextFrameTime = Time.realtimeSinceStartup + 0.025f;   // Add some delay to avoid glitch
        }
```

**Comment by nowsfeky** [comment]
Perfect. That worked. But why is only AILerp working? When I try to use AIPath, the movement doesn't change at all. What can it be ?

**Comment by insthync** [comment]
The demo using AIPath and it's working, you should try see component settings in Seeker, AIPath components
