### ISSUE TITLE
Errors Importing Addon

### ISSUE THREAD

**Issue by NowsfekyBR** [suriyun-mmorpg/UnityMultiplayerARPG_2DAI#2]
Hello. I am getting 3 errors while importing the addon into KIT. I am using KIT version 1.51 and project A * version 4.2.11.
[https://i.imgur.com/4Ii6SHf.png](url)

**Comment by insthync** [comment]
Please download package from https://github.com/insthync/UnityMultiplayerARPG_2DAI/releases, 

Error occuring because I'm updating the core but does not release the latest version yet.

**Comment by NowsfekyBR** [comment]
OK. Thank's.

**Comment by NowsfekyBR** [comment]
I do not know you will put. But you have the option of walking the keyboard arrows or the mobile joystick. It would be nice to put both options, because I see that only the option of clicking on the screen works with this addon.

**Comment by insthync** [comment]
Okay, I will add it in next version

**Comment by insthync** [comment]
Added keyboard WASD and Mobile joystick movement in 1.52. Also have to update this https://github.com/insthync/UnityMultiplayerARPG_2DAI/releases/tag/1.2
