### ISSUE TITLE
Supports WASD controls.

### ISSUE THREAD

**Issue by nowsfeky** [suriyun-mmorpg/UnityMultiplayerARPG_2DAI#3]
Hello ! I tested the last update of the addon, the option to walk with the joystick is working well, but the character walks with the sprite locked, ie does not execute all sprites. And also how can I do so that the player does not go inside the monster.

**Comment by insthync** [comment]
You use AILerp or AIPath?

**Comment by NowsfekyBR** [comment]
I don't know why, but I can only use AILerp. Actually AIPath works fine but I can't take the diagonal movement.

**Comment by insthync** [comment]
So you use AILerp right?, I will try to fix it.

**Comment by insthync** [comment]
Fixed, try 1.2b

**Comment by NowsfekyBR** [comment]
It worked very well. Thanks.
