### ISSUE TITLE
Player is not on the side to attack.

### ISSUE THREAD

**Issue by nowsfeky** [suriyun-mmorpg/UnityMultiplayerARPG_2DAI#4]
When selecting the monster, he goes to the monster to attack correctly, but does not stand next to it, trying to enter the monster because it is a destination point.

**Comment by bma42** [comment]
I've the same problem in 3d with large monsters.

**Comment by insthync** [comment]
This was fixed, if problem still occurring, you can reopen it.

**Comment by nowsfeky** [comment]
Hello insthync! When attacking the mob, the player behaves strangely. It is shaking and entering the mob. I made a video to demonstrate.
[https://www.youtube.com/watch?v=Kthq9Z5PeFE](url)

**Comment by insthync** [comment]
How about monster collider settings, which version are you using, and which AI are you using?, AILerp or AIPath?

**Comment by nowsfeky** [comment]
I can only use AILerp on the monster and the player. I'm using the collider according to the map's node size. Ex: node size map of 1 so the boxcollider is 1. But in fact I just did the sample test without touching anything and the same thing happened. Was there any way the monster was an obstacle? KIT version is 1.54b (2020-03-21)

**Comment by insthync** [comment]
Problem with AILerp again, Have to do many thing to fix this because AILerp is moving in grid while the controller / monster activity was made for non-grid movement. I have to add function that tell state of the AI was reached destination to AstarCharacterMovement2D Controller and then makes controller / monster activity does an attack when AI was reached destination.

**Comment by nowsfeky** [comment]
OK. No problem.

**Comment by insthync** [comment]
I have pushed the update which added ReachedDestination field to AstarCharacterMovement2D, but still have to modifies controller / monster activity. As I tried to changes something it work good.

**Comment by nowsfeky** [comment]
It's ok. I will be waiting for the next release.

**Comment by nowsfeky** [comment]
Hello ! Any predictions to fix?
