### ISSUE TITLE
Player is not on the side to attack. #4

### ISSUE THREAD

**Issue by nowsfeky** [suriyun-mmorpg/UnityMultiplayerARPG_2DAI#6]
Hello ! Any predictions to fix?

**Comment by insthync** [comment]
I will start fix it today

**Comment by nowsfeky** [comment]
Thank's !!!!

**Comment by nowsfeky** [comment]
I think you need to pay attention when you enter the portal too. He was testing and the character does not stop after entering the portal, because when he collides with the BoxCollider he ends up not finding the center of the tile where the target is. With that he keeps coming back and trying to enter the portal again.

**Comment by insthync** [comment]
Yes, seems like I have to create new monster activity class and player character controller class to control character's move target within grids

**Comment by insthync** [comment]
Try 1.3 demo, I've added `PlayerCharacterController2DAI`, you should use it instead of default `PlayerCharacterController`. For the monster, you should use `MonsterActivityComponent2DAI` instead of default `MonsterActivityComponent`.
