### ISSUE TITLE
Camera and player shaking when walking

### ISSUE THREAD

**Issue by grzywkarafal** [suriyun-mmorpg/UnityMultiplayerARPG_2DAI#8]
Hello,

I use AILerp, 

Could you take a look on YT video?

Moving the character is very strange, is the problem with the camera? 

https://www.youtube.com/watch?v=EIenq_CMJag

**Comment by insthync** [comment]
Yes, you may try change camera smooth settings

![Screenshot_780](https://user-images.githubusercontent.com/2697550/142042039-3bf2a771-29d2-4f95-9f23-385a10e98d08.png)

**Comment by grzywkarafal** [comment]
Now camera is ok, but movement is weird
moving still looks weird when i press e.g. A + D

https://www.youtube.com/watch?v=5O3w0Lc1Af4

**Comment by insthync** [comment]
Because it is moving by grid connection, it's good for point click only.

**Comment by insthync** [comment]
When using WASD, it will simulate point-click by to position next to move direction.

**Comment by grzywkarafal** [comment]
Thank you.

Is any way to make movement like this:
https://www.youtube.com/watch?v=IEZBYI0-GUY


?

**Comment by grzywkarafal** [comment]
I mean WASD only

**Comment by insthync** [comment]
Will you do it by yourself ?

**Comment by grzywkarafal** [comment]
unfortunately I have no idea how to do it

I care about such a movement system and combat system as in the video above.

That is:
-WASD / Joystick character movement system in 4 directions. <- like it is, but smooth without weird moves
-System for the movement of monsters in 4 directions on the titles
-The "automatic" combat system, i.e. I mark the monster and every x time it takes damage, depending on where the weapon has x range cells

So i want movement and combat system like in Tibia, Mirage Realms, Rucoy online games.

Are you able to find a moment and estimate how much such solutions would cost?
I would like to pay ofc

**Comment by insthync** [comment]
May create new class which based on AILerp but change movement behaviour

**Comment by grzywkarafal** [comment]
It would be great

**Comment by grzywkarafal** [comment]
Could you find time to fix movement?

**Comment by grzywkarafal** [comment]
Could you find time to fix movement?

**Comment by insthync** [comment]
No time to do it yet

**Comment by grzywkarafal** [comment]
when will you find time for it? :(

**Comment by grzywkarafal** [comment]
bump
